### ISSUE TITLE
Problem with new versioning scheme

### ISSUE THREAD

**Issue by ScottKillen** [Chisel-Team/Chisel#1]
Please see https://github.com/MinecraftModArchive/Dendrology/issues/39 and the attached logs...

The new versioning scheme has broken compatibility with some mods...including Ancient Trees...

Technically, players should not have to upgrade their other mods to use the new version of chisel, right? There has been no API change...

Might I suggest appending CT to the _end_ of the version string...this would make things right again.

**Comment by tterrag1098** [comment]
Yeah we're not sure what to do there. On the one hand, if we continue using normal version numbers, we'll ~~crash~~ clash with Cricket's chisel. But on the other, we have this problem. What do you suggest?

**Comment by ruyanve** [comment]
The error still persists with version 2.9.0
The mod dendrology (Ancient Trees) requires mod versions [chisel@[2.4.0.38,)] to be available

**Comment by tterrag1098** [comment]
Arg, that's my bad. I'll put up a hotfix shortly.

**Comment by tterrag1098** [comment]
Fixed in 2.9.0.3

**Comment by ruyanve** [comment]
Worked like a charm! Cheers!!

**Comment by ScottKillen** [comment]
:+1:

**Comment by lilmoefow** [comment]
is 2.9.0.3 suposed to fix compatibility with More Chisels aswell, or only ancient trees? Cause i'm still getting crashes with More Chisels enabled.  

http://pastebin.com/j18iwdK3

**Comment by TehNut** [comment]
TehNut/MoreChisels#25

**Comment by lilmoefow** [comment]
Cool thanks. When you replied to me yesterday about fixing it i wasn't sure if it was gonna be on your end on chisels :P i probably should have looked a bit harder through your github to see how far along you were
