### ISSUE TITLE
Serverside sounds messed up

### ISSUE THREAD

**Issue by kallezz** [Chisel-Team/Chisel#558]
Other players walking on factoryblocks or laboratoryblocks will play cave ambient sounds.

**Comment by tterrag1098** [comment]
Fixed via 2dd81360bd384f8007a0e8fa5626839e839d9480

**Comment by tofof** [comment]
Has this gone live yet? I'm experiencing this in Chisel-MC1.10.2-0.0.14.33

**Comment by tterrag1098** [comment]
Not yet, I'm planning a release soon.

**Comment by TokaiZockt** [comment]
Any update yet? We're still having some issues with MC Version 1.10.2.  Placing laboratory blocks make other players suffering from all sorts of ambient sounds and walking on them does the same. Any idea how to turn this off till we have a fix so you can work peacefully?
